### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by moth2daflame** [alisdairjsmyth/homebridge-ambiclimate#11]
Getting this error all the time which forces homebridge to quit

[2019-3-4 15:09:00] [AC] getActive: Retrieved mode is undefined
C:\Users\WP\AppData\Roaming\npm\node_modules\homebridge-ambiclimate\node_modules\q\q.js:155
                throw e;
                ^

TypeError: Cannot read property 'value' of undefined
    at C:\Users\WP\AppData\Roaming\npm\node_modules\homebridge-ambiclimate\index.js:87:57
    at C:\Users\WP\AppData\Roaming\npm\node_modules\homebridge-ambiclimate\node_modules\q\q.js:2055:17
    at runSingle (C:\Users\WP\AppData\Roaming\npm\node_modules\homebridge-ambiclimate\node_modules\q\q.js:137:13)
    at flush (C:\Users\WP\AppData\Roaming\npm\node_modules\homebridge-ambiclimate\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by lesterlo** [comment]
I have this problem too
