### ISSUE TITLE
Access Token Error

### ISSUE THREAD

**Issue by chongkwongsheng** [alisdairjsmyth/homebridge-ambiclimate#14]
Having trouble recently even though I have not changed any configurations lately. Wondering if there has been a change in API. I cannot log into https://api.ambiclimate.com

[Homebridge] at Url.parse (url.js:155:3)
[Homebridge] at Object.urlParse [as parse] (url.js:150:13)
[Homebridge] at /home/hoobs/.hoobs/node_modules/node-ambiclimate/ambi-auth.js:114:24
[Homebridge] at processTicksAndRejections (internal/process/task_queues.js:94:5) {
[Homebridge] code: 'ERR_INVALID_ARG_TYPE'
[Homebridge] }
[Homebridge] Access Token Error The "url" argument must be of type string. Received type undefined
[Homebridge] [3/8/2020, 12:41:24 AM] Unhandled Rejection "ReferenceError: nil is not defined".
[Homebridge] [3/8/2020, 12:41:24 AM] ReferenceError: nil is not defined
    at /home/hoobs/.hoobs/node_modules/node-ambiclimate/ambi-auth.js:135:9
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[Homebridge] (node:7692) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[Homebridge] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
[Homebridge] at validateString (internal/validators.js:112:11)

**Comment by chongkwongsheng** [comment]
Issue seems to have fixed itself for some unknown reason despite not doing anything.
